### ISSUE TITLE
[@rollup/plugin-commonjs] with multiple input generates two files instead one

### ISSUE THREAD

**Issue by NikolayMakhonin** [rollup/plugins#1214]
- Rollup Plugin Name: @rollup/plugin-commonjs 
- Rollup Plugin Version: 22.0.0
- Rollup: 2.75.7

### Expected Behavior / Situation
I want to preserve directories and files structure when I use multiple input.
[see this repo](https://github.com/NikolayMakhonin/rollup-multi-input-error)

```
import commonjs from '@rollup/plugin-commonjs'

export default {
  cache: false,
  input: {
    'func1'       : 'src/func1.js',
    'nested/func2': 'src/nested/func2.js',
  },
  output: {
    dir           : 'dist',
    format        : 'cjs',
    exports       : 'named',
    entryFileNames: '[name].js',
    chunkFileNames: '[name].js',
  },
  plugins: [
    commonjs(),
  ],
}
```

I expected such files in the `dist` directory:
```
dist/nested/func2.js
dist/func1.js
```

### Actual Behavior / Situation

but I get this:
```
dist/nested/func2.js
dist/func1.js
dist/func2-4f7093f6.js
```

It works correctly, but I don't want this extra file: `dist/func2-4f7093f6.js`

### Modification Proposal

Add an option to prevent this behavior

**Comment by lukastaegert** [comment]
Most likely fixed by #1108

**Comment by NikolayMakhonin** [comment]
I rollback the @rollup/plugin-commonjs to v21.1.0 and the problem is gone.
It seems to me that this is a bug and not a new feature of v22.0.0

**Comment by lukastaegert** [comment]
It is an unintended side effect of a new feature. But you are free to use an old version.

**Comment by milesj** [comment]
Also getting the double files, and 22.0.1 did not fix the issue.

**Comment by milesj** [comment]
🤔
