### ISSUE TITLE
Undefined exported __moduleExports 

### ISSUE THREAD

**Issue by FbN** [rollup/plugins#266]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 11.0.2
- Rollup Version: 1.32.1
- Operating System (or Browser): Arch Linux 
- Node Version: v12.16.1

### How Do We Reproduce?
Not really sure. Try to roll a mix of ES6 modules and CJS modules that require named export '__moduleExports' when your main package.js has "type": "module".

In my projectI was using snowpack (https://www.snowpack.dev/) with this configuration

/* snowpack.config.js */
module.exports = {
    namedExports: {
        sanctuary: ['__moduleExports'],
        xstream: ['__moduleExports'],
        'sanctuary-def': ['__moduleExports'],
        'sanctuary-type-identifiers': ['__moduleExports']
    },
    rollup: {
        plugins: [pluginNodeBuiltins(), pluginNodeGlobals()]
    }
}

### Expected Behavior
Working rolled web_modules

### Actual Behavior
Exported __moduleExports is undefined

# Proposed solution
Solved this way: https://github.com/FbN/plugins/commit/829219e6c0a4e9c3e458575d4cb9e14b12221477

**Comment by shellscape** [comment]
Please provide a reproduction as per the instructions in the issue template. Otherwise we cannot help.

**Comment by lukastaegert** [comment]
I think I have seen this error when an entry point that is CJS is imported by a file that ends up in another chunk.

**Comment by lukastaegert** [comment]
The error occurs in fact as soon as an entry point that is CJS is imported by a module in the graph. Self-imports count as well. Repro here: https://repl.it/@lukastaegert/rollup-plugin-repro

**Comment by FbN** [comment]
Thank you @lukastaegert for the clarification and test. Do you think my patch is a good solution or may cause collateral damages?

**Comment by csr632** [comment]
Here is another reproduce repo: https://github.com/csr632/rollup-issue

**Comment by csr632** [comment]
@danielgindi 
Could you take a look at this?

**Comment by csr632** [comment]
Oh, this is already fixed by latest commonjs plugin in master branch, but the fix is not published into npm yet. This issue can be closed after it is published.

**Comment by shellscape** [comment]
@csr632 Please _do not post successive replies_ - use the Edit function on the first.

**Comment by derolf** [comment]
I just hit this problem. "__moduleExports" appears when importing files that are also entry points.

`rollup v2.26.10`

**Comment by ftaiolivista** [comment]
The problem still exists in snowpack using plugin-commonjs@16.0.0

Some deps use import with .default creating problems.

I solved patching plugin-commonjs@16.0.0 to always set default to the namespace when ther is not allready a default defined.

```
diff --git a/node_modules/@rollup/plugin-commonjs/dist/index.js b/node_modules/@rollup/plugin-commonjs/dist/index.js
index 32dd0de..e271a8a 100644
--- a/node_modules/@rollup/plugin-commonjs/dist/index.js
+++ b/node_modules/@rollup/plugin-commonjs/dist/index.js
@@ -55,7 +55,9 @@ const HELPERS = `
 export var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
 
 export function getDefaultExportFromCjs (x) {
-	return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, 'default') ? x['default'] : x;
+    return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, 'default') ?
+        (x['default'].default = x.default, x['default'])
+        : x;
 }
 
 export function createCommonjsModule(fn, basedir, module) {

```
