### ISSUE TITLE
[TypeScript] Error: Unexpected token

### ISSUE THREAD

**Issue by Jack-Works** [rollup/plugins#892]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.2.1
- Rollup Version: 2.50.5
- Operating System (or Browser): Windows
- Node Version: 16.2.0
- Link to reproduction _(⚠️ read below)_: https://github.com/Jack-Works/rollup-plugin-bug-287-reproduce/

```shell
> npx rollup -c
```

### Expected Behavior

Can compile

### Actual Behavior

> [!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### Additional Information

related #287

**Comment by shellscape** [comment]
Duplicate of #287. Please comment on the other issue. If youd like to see it reopened/resolved pleade consider contributing.

**Comment by Jack-Works** [comment]
> Please comment on the other issue

It's locked and unresolved.

**Comment by Jack-Works** [comment]
Oh is this resolved in #818?

**Comment by shellscape** [comment]
Thanks, I didn't realized it was locked. Yes, #818 was targeted to resolve _most_ of the problems that caused the error. Given the size of the framework, we couldn't claim there aren't cases which it didn't resolve. That fix did land in https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md#v821. I'll reopen this as a separate issue, separate reproduction.

**Comment by waynevanson** [comment]
> I'll reopen this as a separate issue, separate reproduction.

Hi @shellscape, I'm looking to follow the trail but can't see the issue you've mentioned. If you've made it, what issue was it?

**Comment by ZYinMD** [comment]
For those who still get this issue, fwiw, check if the parent directory or grand parent directory is a symlink. If yes, cd into the actual directory and try again.

**Comment by kibin** [comment]
I had the same problem (plugin-typescript@11.0.0, rollup@3.20.2, node@18.15.0, typescript@4.9.5) and could only resolve it after extensive reading of original thread, especially [this comment](https://github.com/rollup/plugins/issues/287#issuecomment-701923921). thought I need to share my findings for others who struggle as well.
seems like `outDir` field is still a major offender for this plugin. code isn't compiling until it's removed from `tsconfig.json`.
